name: Build Mihomo Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Build Binary
        run: |
          if (Test-Path "go.mod") { rm go.mod }
          go mod init mihomo-run
          # 下载 windows 扩展包
          go get golang.org/x/sys/windows
          go mod tidy
          $env:GOOS="windows"
          # 调试建议：先去掉 -H windowsgui 看看有没有报错输出
          go build -ldflags="-H windowsgui -s -w" -o mihomo-run.exe main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mihomo-run-binary
          path: mihomo-run.exe
