name: Build Mihomo Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Build Binary
        run: |
          if (Test-Path "go.mod") { rm go.mod }
          go mod init mihomo-run
          go mod tidy
          # 强制指定 GOOS 为 windows
          $env:GOOS="windows"
          go build -ldflags="-H windowsgui -s -w" -o mihomo-run.exe main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mihomo-run-binary
          path: mihomo-run.exe
